---
test:
  workers:
    type: local
    number: 1

  rounds:
  - label: initLedger
    txNumber: 
    - 1
    rateControl:
      type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/zk-voting/initLedger.js

  - label: common
    txDuration: 
    - 120
    rateControl:
    - type: fixed-rate
      opts:
        tps: 25
    callback: ../inventory/blockchain/benchmark/zk-voting/common.js

  - label: readBlockchain
    txNumber: 
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/zk-voting/doNothing.js

monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
